### ISSUE TITLE
paperless ngx add-on Home Assistant / Support for Tika and Gotenberg

### ISSUE THREAD

**Issue by Aliofredi** [BenoitAnastay/paperless-home-assistant-addon#134] opened 2024-04-12 11:51 UTC
Hi, thanks for the work done for the add-on so far. Does the HA paperless ngx add-on provide support for Tika & Gotenberg which is to my knowledge a prerequisite to process doc files or eml emails ? And if yes, how do I enable this ? 

Next question would be: is their an import / export process available in the HA paperless add-on to migrate from / to other hardware platforms like eg. paperless docker installation on a NAS?

Thank you very much

**Comment by BenoitAnastay** [comment] 2024-04-12 11:55
Duplicate of #114 

I need to create a side add-on

**Closed by BenoitAnastay** 2024-04-12 11:55 UTC
Labels: duplicate
