### ISSUE TITLE
add support for odt documents?

### ISSUE THREAD

**Issue by prankousky** [BenoitAnastay/paperless-home-assistant-addon#145] opened 2024-05-15 11:03 UTC
Hi,

I tried running paperless-ngx locally on my PC as regular docker container. There was an option to not only work with PDF files, but also regular documents, such as ODT (libre office writer) or, I believe, docx (ms word).

Can this be enabled somehow, or, if not, might it be a feature that could be implemented? Having this on Home Assistant now, I'd love to finally start organizing my documents, but having to convert previous correspondence from odt to pdf would not be ideal.

Thank you in advance for your help :)

**Comment by BenoitAnastay** [comment] 2024-05-15 12:37
I haven't the time to create a Tika and Gotenberg add-on, but there's already a way to handle it with portainer add-on.

Duplicate of #114

**Closed by BenoitAnastay** 2024-05-15 12:37 UTC
